version: '3'

services:
  providers_microservice:
    container_name: providers_microservice
    build: ./providers-microservice
    volumes:
      - ./providers-microservice:/usr/app
    ports:
      - '50052:50052'
  
  gateway:
    container_name: pay_on_time_gateway
    build: ./gateway
    volumes:
      - ./gateway:/usr/app
    ports:
      - '5000:5000'
