version: '3'

services:
  pay_on_time_gateway:
    container_name: pay_on_time_gateway
    build: ./pay-on-time-gateway
    volumes:
      - ./pay-on-time-gateway:/pay-on-time
    ports:
      - '5000:5000'
    networks:
      pay_on_time_net:
        ipv4_address: 200.0.0.20

  mongodb:
    container_name: mongodb
    image: mongo:4.2.8-bionic
    ports:
      - '27017:27017'
    networks:
      pay_on_time_net:
        ipv4_address: 200.0.0.11

  providers_microservice:
    container_name: providers_microservice
    build: ./providers-microservice
    volumes:
      - ./providers-microservice:/pay-on-time
    ports:
      - '50052:50052'
    depends_on:
      - mongodb
    networks:
      pay_on_time_net:
        ipv4_address: 200.0.0.21

networks:
  pay_on_time_net:
    driver: bridge
    ipam:
      config:
        - subnet: 200.0.0.1/24
